### ISSUE TITLE
[Bug]: line after perior+enter but not enter

### ISSUE THREAD

**Issue by huachuman** [Quorafind/Obsidian-Better-Order-List#1]
### Bug Description

Line after perior+enter but not enter

### Relevant Screenshot

![GIF 1-12-2024 6-06-51 AM](https://github.com/Quorafind/Obsidian-Better-Order-List/assets/125603964/4ac5311d-e703-412f-8acc-c5e414d2c632)

### Obsidian Version

1.5.3

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
Thanks for report. Will be fixed soon.

**Comment by Quorafind** [comment]
Got fixed already.

**Comment by huachuman** [comment]
Ironic that the word "deleted" was deleted from my bug report... early mornings with no coffee... glad this got fixed. Thank you !!!

**Comment by huachuman** [comment]
Weird... seems to be happening again.
